version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: anfutrans-db
    restart: always
    environment:
      POSTGRES_USER: anfutrans_app
      POSTGRES_PASSWORD: CambiarPasswordSegura
      POSTGRES_DB: anfutrans_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
